changelog:
  categories:
    - title: ✨ Features
      labels:
        - feature
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - bug
        - fix
    - title: 🧰 Maintenance
      labels:
        - chore
        - maintenance
        - refactor
    - title: 🧪 Tests
      labels:
        - test
    - title: 📚 Documentation
      labels:
        - docs
    - title: Other changes
      labels:
        - '*' 
